### ISSUE TITLE
Optional SimpleAction behaviour is breaking Communication

### ISSUE THREAD

**Issue by 0Nel** [dfki-ric/robot_remote_control#25]
In the most recent [commit](https://github.com/dfki-ric/robot_remote_control/commit/642468a282855ec5a0f2ee909f04984f90b7ff3e) the following lines were added:

```cpp
    /**
     * @brief if the optional initSimpleactions is called on the controlledRobot, the available actions can be requested.
     */
    robot_remote_control::SimpleActions simpleactions;
    controller.requestSimpleActions(&simpleactions);
    simpleactions.PrintDebugString();
```

This works fine if the ControlledRobot has called the initSimpleactions method. However it crashes with a really unspecific error, if not:

```
terminate called after throwing an instance of 'zmq::error_t'
  what():  Operation cannot be accomplished in current state
Aborted (core dumped)
```

Since the initSimpleAction is optional on the ControlledRobot side and it would be nice, if the RobotControllerMain Demo would still work or at least give a more helpful error message, I would suggest to catch the zmq to provide a more detailed error or set the availableSimpleActions to zero.

**Comment by 0Nel** [comment]
Actually calling initSimpleActions is not enough. The passed simpleaction reference has to have at least one element.

**Comment by planthaber** [comment]
This error comes up if the REQ/REP socket of ZMQ in the ControlledRobot was unable to Reply (robotcontroller chrashes). Then the ControlledRobot is getting stuck in this state and won't accept a new reply, thus the "Operation cannot be accomplished in current state" message.

Normally this should already should have been fixed by these lines: https://github.com/dfki-ric/robot_remote_control/blob/master/src/Transports/TransportZmq.cpp#L22-L23
