### ISSUE TITLE
RRC builds up latency if more data than possible to transmit it generated

### ISSUE THREAD

**Issue by chhtz** [dfki-ric/robot_remote_control#39]
E.g., when trying to transmit point clouds with full resolution and frequency over WiFi, RRC seems to buffer every packet which builds up a lot of latency over time.
Very often it would make more sense to only transmit the most recent data (of course, this depends on the use case, so making it configurable would be nice -- maybe there is an option for that already?).

**Comment by planthaber** [comment]
There are only options on the receiving side, as on the sender side the messages are directly handed to the transport (ZMQ).

There a socket options for ZMQ on the sender (https://stackoverflow.com/questions/43791198/zeromq-buffer-size-v-s-high-water-mark). But as in rrc all telemetry is sent on a single socket, limiting it would probably result in a lot of "small" messages being dropped while the big messages (point clouds) are being processed. 

I'd also expect that you'll have to tune both values to have it functioning as expected, as the number of messages is not really related to their size in bytes. 

I'd rather tune the send intervals of your Telemetry types than trying to solve it on the buffer level because it gives you control about which message type is transmitted.

In your implementation, you can use the included SendTimers class to determine if a new message (e.g. point cloud) has to be sent to match a given freqeuncy (if a set time for a type has beed expired and the message should be sent again):

https://github.com/dfki-ric/robot_remote_control/blob/master/src/Tools/SendTimers.hpp

The class holds n configurations for timed sends. In its constructor, you can set it to a single timer if you want, or use the Enums from message.h to access the timers (and set the size), like describes in the header.

```cpp
SendTimers pcloud_timer(1);
pcloud_timer.setSendSpeed(0, 10000 ) // send entry 0 every 10000ms

while (true) { // main loop of your program
    if (getNextCloud) { // read the latest cloud from your robot framework
        if (pcloud_timer.isSendRequired(0)) {
             telemetry->setPointCloud(cloud);
        }
    }
}

**Comment by chhtz** [comment]
Based on this https://stackoverflow.com/questions/68173972/how-to-prevent-buffering-latency-with-pub-sub I was trying to enable the "conflate" option on the sender side, which appears to work (see below). I agree that this is not ideal. But I don't think just reducing the frequency is stable enough (e.g., if bandwidth drops unexpectedly) -- unless we somehow have control what the current throughput is.

```
--- a/src/Transports/TransportZmq.cpp
+++ b/src/Transports/TransportZmq.cpp
@@ -63,6 +63,7 @@ void TransportZmq::connect() {
             }
             case PUB: {
                 socket = std::shared_ptr<zmq::socket_t>(new zmq::socket_t(*(context.get()), ZMQ_PUB));
+                socket->setsockopt(ZMQ_CONFLATE, 1);  // FIXME testing conflate option (==only keep last message)
                 socket->bind(addr);
                 break;
             }
diff --git a/src/Types/Conversions/ros/tf/StampedTransform.hpp b/src/Types/Conversions/ros/tf/StampedTransform.hpp
```

**Comment by planthaber** [comment]
If it works, we could add a option to enable it manually in the Zmqtransport implementation, so it could be enabled before handing the transport to the ControlledRobot implementation.

**Comment by planthaber** [comment]
Could be related to https://github.com/zeromq/libzmq/issues/3323, I don't know which zmq version is currently used in your case or OS. But the issue should be already fixed.

Still, I think ZMQ_SNDHWM is the better option here.

Rather than adding a third transport, you can also use a second instance of your rrc implementation on both sides running on other ports/sockets. Then you can enable ZMQ_CONFLATE or ZMQ_SNDHWM just on the socket where the big data is moved.

RRC wasn't originally designed to transmit big data in the telemetry (point clouds were meant to be requested as "maps" only on demand), hence the name "robot remote control" and not "robot data interface". But using a 2nd instance of ControlledRobot and RobotController solves the big data issue pretty well.
