### ISSUE TITLE
Additional VALUE_STRING type for SimpleActionType would be great

### ISSUE THREAD

**Issue by moooeeeep** [dfki-ric/robot_remote_control#42]
Currently we have int, float, trigger: https://github.com/dfki-ric/robot_remote_control/blob/master/src/Types/RobotRemoteControl.proto#L330

I think a string type would be a great addition. Not sure how difficult it would be to add this. Or is the functionality already there?

**Comment by planthaber** [comment]
Adding it is easy, but the string field would be needed to be added in the Simpleaction type: https://github.com/dfki-ric/robot_remote_control/blob/master/src/Types/RobotRemoteControl.proto#L310

BUT: For sending a string as command value would make the protocol less generic because the user (e.g. using the CLI) needs to know the strings that can be set.

The way that implements similar functionality is using "Named Values", it is sadly only hinted in the doc: https://github.com/dfki-ric/robot_remote_control/tree/master/doc#defining-actions

But, when you use the "initSimpleActions" function on the ControlledRobot side, you can report the "type" i.e. [SimpleActionDef](https://github.com/dfki-ric/robot_remote_control/blob/master/src/Types/RobotRemoteControl.proto#L317). Within this SimpleActionDef you can define "NamedValues" which are Name-Value pairs, actually like an enum that also supports floats.

The robotcontroller can read these NamedValues and then knows which Name (your requested string value) resolves to which value in the SimpleAction. 

Its a bit more complicated than sending a string, but this creates an readable interface for the robot that can be used without prior knowledge. At least when the actions and values have descriptive names.

On the ControlledRobot use The ControlledRobot:initSimpleactions():
```cpp
SimpleActions myactions;
SimpleAction* mystringaction->myactions.add_action();
mystringaction->set_name("Control Mode");
SimpleActionDef* def = mystringaction->add_type();
def->set_type(VALUE_INT);
NamedValue* nameentry = def->add_value_names();
nameentry->set_name("BASE");
nameentry->set_value(1);
nameentry->set_name("ARM");
nameentry->set_value(2);

myself->initSimpleActions(myactions);
```

The RobotController can request the action definition by RobotController::requestSimpleActions

So you could e.g. request the string value pairs and set up a std::map translating the string values to the int values which are then sent as the command value.

Btw: The CLI will also request the available actions and even provide tab-completion with the names, which are then also replaced with the actual numbers before sending those commands.
